DROP TABLE rating IF EXISTS CASCADE;
DROP TABLE votes IF EXISTS CASCADE ;
DROP TABLE dishes IF EXISTS CASCADE ;
DROP TABLE restaurants IF EXISTS;
DROP TABLE users IF EXISTS CASCADE;

DROP SEQUENCE global_seq IF EXISTS CASCADE ;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  role             VARCHAR(255)
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE restaurants
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  date             DATE DEFAULT now()      NOT NULL
);
CREATE UNIQUE INDEX restaurants_unique_name_on_date_idx ON restaurants (name, date);

CREATE TABLE dishes
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  price            INT                     NOT NULL,
  restaurant_id    INTEGER                 NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);

CREATE TABLE votes
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  restaurant_id    INTEGER                 NOT NULL,
  user_id          INTEGER                 NOT NULL,
  date             DATE DEFAULT now()      NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);

CREATE TABLE rating
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  restaurant_id    INTEGER                 NOT NULL,
  date             DATE DEFAULT now()      NOT NULL,
  summary_votes    INTEGER DEFAULT 0       NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);